{
  "vocab": "aA\u00e0\u00c0\u1ea3\u1ea2\u00e3\u00c3\u00e1\u00c1\u1ea1\u1ea0\u0103\u0102\u1eb1\u1eb0\u1eb3\u1eb2\u1eb5\u1eb4\u1eaf\u1eae\u1eb7\u1eb6\u00e2\u00c2\u1ea7\u1ea6\u1ea9\u1ea8\u1eab\u1eaa\u1ea5\u1ea4\u1ead\u1eacbBcCdD\u0111\u0110eE\u00e8\u00c8\u1ebb\u1eba\u1ebd\u1ebc\u00e9\u00c9\u1eb9\u1eb8\u00ea\u00ca\u1ec1\u1ec0\u1ec3\u1ec2\u1ec5\u1ec4\u1ebf\u1ebe\u1ec7\u1ec6fFgGhHiI\u00ec\u00cc\u1ec9\u1ec8\u0129\u0128\u00ed\u00cd\u1ecb\u1ecajJkKlLmMnNoO\u00f2\u00d2\u1ecf\u1ece\u00f5\u00d5\u00f3\u00d3\u1ecd\u1ecc\u00f4\u00d4\u1ed3\u1ed2\u1ed5\u1ed4\u1ed7\u1ed6\u1ed1\u1ed0\u1ed9\u1ed8\u01a1\u01a0\u1edd\u1edc\u1edf\u1ede\u1ee1\u1ee0\u1edb\u1eda\u1ee3\u1ee2pPqQrRsStTuU\u00f9\u00d9\u1ee7\u1ee6\u0169\u0168\u00fa\u00da\u1ee5\u1ee4\u01b0\u01af\u1eeb\u1eea\u1eed\u1eec\u1eef\u1eee\u1ee9\u1ee8\u1ef1\u1ef0vVwWxXyY\u1ef3\u1ef2\u1ef7\u1ef6\u1ef9\u1ef8\u00fd\u00dd\u1ef5\u1ef4zZ0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ ",
  "device": "cuda:0",
  "seq_modeling": "transformer",
  "transformer": {
    "d_model": 256,
    "nhead": 8,
    "num_encoder_layers": 6,
    "num_decoder_layers": 6,
    "dim_feedforward": 2048,
    "max_seq_length": 1024,
    "pos_dropout": 0.1,
    "trans_dropout": 0.1
  },
  "optimizer": {
    "max_lr": 0.0003,
    "pct_start": 0.1
  },
  "trainer": {
    "batch_size": 32,
    "print_every": 200,
    "valid_every": 4000,
    "iters": 100000,
    "export": "./weights/transformerocr.pth",
    "checkpoint": "./checkpoint/transformerocr_checkpoint.pth",
    "log": "./train.log",
    "metrics": null
  },
  "dataset": {
    "name": "data",
    "data_root": "./img/",
    "train_annotation": "annotation_train.txt",
    "valid_annotation": "annotation_val_small.txt",
    "image_height": 32,
    "image_min_width": 32,
    "image_max_width": 512
  },
  "dataloader": {
    "num_workers": 3,
    "pin_memory": true
  },
  "aug": {
    "image_aug": true,
    "masked_language_model": true
  },
  "predictor": {
    "beamsearch": false
  },
  "quiet": false,
  "pretrain": "https://vocr.vn/data/vietocr/vgg_transformer.pth",
  "weights": "https://vocr.vn/data/vietocr/vgg_transformer.pth",
  "backbone": "vgg19_bn",
  "cnn": {
    "pretrained": true,
    "ss": [
      [
        2,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ]
    ],
    "ks": [
      [
        2,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ]
    ],
    "hidden": 256
  }
}